# Generated by Django 3.1.2 on 2020-11-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_ill_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dateBirth',
            field=models.DateField(help_text='YYYY-MM-DD'),
        ),
    ]
